name: npm

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Generate html
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: npm run docs
    - run: git config --local user.email "action@github.com"
    - run: git config --local user.name "GitHub Action"
    - run: git add docs/*
    - run: git commit -m "自動docsビルド"
    - run: git push
